version: '3'
services:
  web:
    build: ./web_app
    image: tasmota_heating_web
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped
  app:
    build: ./tasmota_control
    image: tasmota_heating_app
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - "6379:6379"